baseurl = "/dankgenetics.crypto"
languageCode = "en-us"
paginate = 5
relativeUrls = true
theme = "terminal"
[languages.en]
copyright = ""
keywords = ""
languageName = "English"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "the frostiest nugz harvested weekly"
title = "dank.genetics.crypto"
[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "dank.genetics.crypto"
[params]
centerTheme = false
contentTypeName = "posts"
fullWidthTheme = false
showLanguageSelector = false
showMenuItems = 4
themeColor = "green"
sectionPagesMenu = "main"